version: "3.9"

services:
  reporter:
    image: vladovsiychuk/demo-reporter:latest
    ports:
      - '8030:8080'

  dynamodb:
    image: amazon/dynamodb-local:2.6.1
    ports:
      - '8000:8000'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:5.1.3
    ports:
      - '8001:8001'

  mysql:
    image: mysql:8.4.5
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: justtrack

  redis:
    image: redis:8.0-alpine
    ports:
      - '6379:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    ports:
      - '8081:8081'
    environment:
      REDIS_HOSTS: redis
      REDIS_PORT: redis:6379

  kafka:
    image: apache/kafka:3.9.1
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL_CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,INTERNAL_CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - '8040:8080'
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka:29093
